server {
    listen 80;
    server_name
        hhy-api.orbexa.cc
        hhy-admin.orbexa.cc
        hhy-h5.orbexa.cc
        hhy-yq.orbexa.cc
        hhy-download.orbexa.cc
        hhy-ws.orbexa.cc;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
